/**
 * PHASE 1: DATA TYPES
 * 
 * This file defines TypeScript interfaces (like blueprints/schemas)
 * that describe the shape of data used throughout the app.
 * Think of these like class definitions in Python - they tell TypeScript
 * what properties an object should have and what types they should be.
 */

/**
 * Figure Interface
 * ================
 * Represents a SINGLE dance move/step (e.g., "Feather Step", "Promenade")
 * This is a "master" definition - stored once in the database,
 * but can be referenced by many routines.
 * 
 * Usage: When user views a specific dance's figures page, they see a list of Figure objects.
 *        When user adds a figure to their routine, a Figure is wrapped in a RoutineStep.
 */
export interface Figure {
  // Unique identifier, generated by database (UUID)
  // Used to reference this specific figure across the app
  id: string

  // Display name of the dance move (readable to humans)
  // Example: "Feather Step", "Natural Turn", "Chassé"
  name: string

  // Difficulty rating on a scale (probably 0-5)
  // 0 = not rated
  // 1-5 = star difficulty
  // Used for filtering figures by difficulty in the UI
  difficulty: number

  // Additional info/description about the figure
  // Example: "Leads forward, requires good connection"
  note: string

  // Full YouTube video URL demonstrating this figure
  // Example: "https://www.youtube.com/watch?v=abc123"
  youtube_url: string

  // When to START playing the video (in seconds)
  // Example: 30 = start from 30 seconds into the video
  start_time: number

  // When to STOP playing the video (in seconds)
  // Example: 45 = stop at 45 seconds
  // Together with start_time, these set the "clip" of the video to show
  end_time: number
}

/**
 * RoutineStep Interface
 * =====================
 * Represents ONE STEP in a user's routine sequence.
 * A routine is made up of many RoutineSteps in order.
 * 
 * Key insight: A Figure is reusable (exists in database once),
 *              but a RoutineStep is unique to one routine at one position.
 * 
 * Example:
 *   Routine: "My Waltz"
 *     - Step 1: Figure "Feather Step"
 *     - Step 2: Figure "Natural Turn"
 *     - Step 3: Figure "Feather Step" (SAME figure as step 1, but different step)
 * 
 * Usage: RoutineBuilder displays a list of RoutineSteps in order.
 *        When user drags a Figure into the builder, a new RoutineStep is created.
 */
export interface RoutineStep {
  // Unique identifier FOR THIS STEP in THIS routine
  // NOT the same as figure.id - each position in routine gets its own ID
  // Used internally for React keys, sorting, removal, etc.
  // Generated with uuid() when a figure is added
  stepId: string

  // Reference to the Figure object at this step
  // Contains all the figure data (name, youtube_url, difficulty, etc.)
  // Can navigate: step.figure.name, step.figure.youtube_url, etc.
  figure: Figure
}

/**
 * Routine Interface
 * =================
 * Represents a COMPLETE dance routine (a choreographed sequence).
 * This is what user SAVES to the database.
 * One routine = one record in the "routines" table in Supabase.
 * 
 * Usage: When user saves their choreography, a Routine object is sent to Supabase.
 *        When user loads a saved routine, a Routine is fetched from Supabase.
 *        "My Routines" page displays a list of Routine objects.
 */
export interface Routine {
  // Unique identifier for this saved routine
  // Generated by Supabase (UUID)
  // Used to retrieve, update, or delete this routine later
  id: string

  // User-given name for this routine
  // Example: "Argentine Tango - Competition 2026"
  // Editable by user in the UI
  name: string

  // Which dance style this routine is for
  // Example: "waltz", "tango", "quickstep"
  // Used to group/filter routines, and to match figures in the figures table
  dance_style: string

  // When this routine was created (ISO timestamp)
  // Example: "2026-03-16T10:30:00Z"
  // Automatically set by Supabase, used for sorting in "My Routines"
  created_at: string

  // Array of RoutineSteps in ORDER
  // This is the actual choreography - the sequence of moves
  // steps[0] = first move, steps[1] = second move, etc.
  // Can be reordered by dragging in the UI
  steps: RoutineStep[]
}

/**
 * YouTube Player Types
 * ====================
 * Shared types for YouTube IFrame API integration.
 * Used by both FigurePanel (preview) and RoutinePlayer (main video).
 */
export interface YTPlayer {
  playVideo: () => void
  pauseVideo: () => void
  seekTo: (seconds: number) => void
  setPlaybackRate: (rate: number) => void
  destroy: () => void
  getCurrentTime: () => number
}

declare global {
  interface Window {
    YT: {
      Player: new (elementId: string, options: Record<string, unknown>) => YTPlayer
      PlayerState: Record<string, number>
    }
    onYouTubeIframeAPIReady: () => void
  }
}
